/**
 * GeoJSON 폴리곤 이름 → jeongbiData.ts 이름 매핑
 * jeongbiName에 jeongbiData.ts의 name 값 그대로 입력하세요.
 * 주석 해제 후 jeongbiName만 채우면 됩니다.
 */
export const JEONGBI_NAME_MAP: { polyName: string; jeongbiName: string }[] = [
  // { polyName: "영주1재건축정비구역", jeongbiName: "" },
  // { polyName: "서대신6재개발정비구역", jeongbiName: "" },
  // { polyName: "서대신3 주택재개발", jeongbiName: "" },
  // { polyName: "서대신4 주택재개발", jeongbiName: "" },
  // { polyName: "서대신5재개발 정비구역", jeongbiName: "" },
  // { polyName: "부민3 재개발사업", jeongbiName: "" },
  // { polyName: "아미4 주거환경개선 정비구역", jeongbiName: "" },
  // { polyName: "남부민1주거환경 관리사업", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)_E", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)_D", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)_B", jeongbiName: "" },
  // { polyName: "동대신1 재개발정비구역", jeongbiName: "" },
  // { polyName: "서대신7주택재개발", jeongbiName: "" },
  // { polyName: "서대신1주택재개발정비구역", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)_A", jeongbiName: "" },
  // { polyName: "주택개량 재개발", jeongbiName: "" },
  // { polyName: "부민동 주택재개발", jeongbiName: "" },
  // { polyName: "서대신2주택재개발정비구역", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)_C", jeongbiName: "" },
  // { polyName: "범일2재개발구역", jeongbiName: "" },
  // { polyName: "초량1-3 도시환경정비구역", jeongbiName: "" },
  // { polyName: "범일3 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "영주1 정비구역", jeongbiName: "" },
  // { polyName: "좌천2 주거환경개선구역", jeongbiName: "" },
  // { polyName: "범일3-1도시환경정비구역", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "청학1 재건축사업", jeongbiName: "" },
  // { polyName: "동삼1 재건축사업 정비계획 결정 및 정비구역 지정 고시", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "연지4 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "개금2 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "양정4 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "양정1 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "가야5 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "연지2 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "가야1 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "전포1-1재개발 정비구역", jeongbiName: "" },
  // { polyName: "가야3 재개발정비구역", jeongbiName: "" },
  // { polyName: "양정2 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "당감1-1 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "아파트지구에서 정비구역으로 변경<도시계획과-2004(2012.2.23)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "당감1 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(구거)", jeongbiName: "" },
  // { polyName: "복산1 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "온천1 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "안락1 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "명장5 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "수안1 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "공동주택용지", jeongbiName: "" },
  // { polyName: "낙민1 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "공동주택용지", jeongbiName: "" },
  // { polyName: "사직2 재개발 정비구역", jeongbiName: "" },
  // { polyName: "공동주택용지", jeongbiName: "" },
  // { polyName: "온천5 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "사직3 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "명서1 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "하수도(구거)", jeongbiName: "" },
  // { polyName: "사직5 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "명장3 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "수안3 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "명륜2재건축사업정비구역", jeongbiName: "" },
  // { polyName: "명장1주택재개발", jeongbiName: "" },
  // { polyName: "근린생활시설용지", jeongbiName: "" },
  // { polyName: "공동주택용지", jeongbiName: "" },
  // { polyName: "근린생활시설용지", jeongbiName: "" },
  // { polyName: "공동주택용지", jeongbiName: "" },
  // { polyName: "명장2 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "수안1 재건축 정비구역 토지정보과-8259(2022.06.22.)호로 도시관리계획선 정정", jeongbiName: "" },
  // { polyName: "안락3주택재건축", jeongbiName: "" },
  // { polyName: "안락1재건축정비구역", jeongbiName: "" },
  // { polyName: "정비기반시설（도로）", jeongbiName: "" },
  // { polyName: "일반도로", jeongbiName: "" },
  // { polyName: "도로1", jeongbiName: "" },
  // { polyName: "도로2", jeongbiName: "" },
  // { polyName: "정비기반시설(도로3)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로2)", jeongbiName: "" },
  // { polyName: "정비기반시설 (도로1)", jeongbiName: "" },
  // { polyName: "문현6 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "대연2주택재개발 정비구역", jeongbiName: "" },
  // { polyName: "우암1 재개발 정비구역", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "정비기반시설(도로)", jeongbiName: "" },
  // { polyName: "대연8재개발정비구역", jeongbiName: "" },
  // { polyName: "문현1 재개발정비구역", jeongbiName: "" },
  // { polyName: "금곡2-1주택재개발정비구역", jeongbiName: "" },
  // { polyName: "화명3주택재개발정비구역", jeongbiName: "" },
  // { polyName: "화명2주택재개발정비구역", jeongbiName: "" },
  // { polyName: "구포1 주거환경관리사업 정비구역", jeongbiName: "" },
  // { polyName: "화명2재건축정비구역", jeongbiName: "" },
  // { polyName: "덕천2-1주택재건축정비구역", jeongbiName: "" },
  // { polyName: "정비기반시설(공원)", jeongbiName: "" },
  // { polyName: "만덕4 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "덕천2주택재건축정비구역", jeongbiName: "" },
  // { polyName: "재송5 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "(자세한 사항은 별도문의 : 건축과)", jeongbiName: "" },
  // { polyName: "(자세한사항은 별도문의 : 건축과)", jeongbiName: "" },
  // { polyName: "반여3-1 주택재건축", jeongbiName: "" },
  // { polyName: "우동 6주택재개발 정비구역", jeongbiName: "" },
  // { polyName: "우동2 재개발 정비구역", jeongbiName: "" },
  // { polyName: "반여4 재건축 정비구역", jeongbiName: "" },
  // { polyName: "중동3도시환경정비구역", jeongbiName: "" },
  // { polyName: "재송2재개발정비구역", jeongbiName: "" },
  // { polyName: "(자세한사항은 별도문의 : 건축과)", jeongbiName: "" },
  // { polyName: "중동1주택재개발정비구역", jeongbiName: "" },
  // { polyName: "반여1-1 재개발정비구역", jeongbiName: "" },
  // { polyName: "중동5재개발정비구역", jeongbiName: "" },
  // { polyName: "재송2 주택재건축정비구역", jeongbiName: "" },
  // { polyName: "당리2 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "하단2 재개발사업", jeongbiName: "" },
  // { polyName: "하단3 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "하단1 재건축 정비구역", jeongbiName: "" },
  // { polyName: "감천2 주택재개발 정비구역", jeongbiName: "" },
  // { polyName: "다대4 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "도-1", jeongbiName: "" },
  // { polyName: "도-2", jeongbiName: "" },
  // { polyName: "신평1 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "부곡2주택재개발정비구역", jeongbiName: "" },
  // { polyName: "장전3주택재개발정비구역", jeongbiName: "" },
  // { polyName: "장전1주택재개발정비구역", jeongbiName: "" },
  // { polyName: "구서5 재건축 정비구역", jeongbiName: "" },
  // { polyName: "명서1 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "구서2 주택재건축정비구역", jeongbiName: "" },
  // { polyName: "구서3 재건축 정비구역", jeongbiName: "" },
  // { polyName: "부곡금강아파트 주택재건축정비구역", jeongbiName: "" },
  // { polyName: "연산14 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "연산5 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "거제1 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "연산6 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "연산13 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "연산11 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "거제2 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "연산5 재건축 정비구역", jeongbiName: "" },
  // { polyName: "연산4 주택재건축", jeongbiName: "" },
  // { polyName: "연산3 재개발 정비구역", jeongbiName: "" },
  // { polyName: "거제1주택재개발", jeongbiName: "" },
  // { polyName: "양정2주택재개발", jeongbiName: "" },
  // { polyName: "거제2 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "부산광역시 고시 제2026-104호", jeongbiName: "" },
  // { polyName: "광안동 379-17번지의 등록사항정정(토지대장등록)으로 인한 구역계 변경없는 면적 증가", jeongbiName: "" },
  // { polyName: "광안1주택재개발정비구역", jeongbiName: "" },
  // { polyName: "주택재건축정비사업-남천2주택재건축구역", jeongbiName: "" },
  // { polyName: "민락2재개발정비구역", jeongbiName: "" },
  // { polyName: "광안2주택재건축구역", jeongbiName: "" },
  // { polyName: "주례3 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "주례4 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "주례1 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "주례2 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "학장1 재건축사업 정비구역", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "공공보행통로", jeongbiName: "" },
  // { polyName: "괘법1 재개발사업 정비구역", jeongbiName: "" },
  // { polyName: "상업시설용지1", jeongbiName: "" },
  // { polyName: "종교용지2", jeongbiName: "" },
  // { polyName: "종교용지1", jeongbiName: "" },
  // { polyName: "상업시설용지2", jeongbiName: "" },
  // { polyName: "엄궁3 재개발 정비구역", jeongbiName: "" },
  // { polyName: "엄궁지구 주택 재건축정비구역", jeongbiName: "" },
  // { polyName: "주례2 재개발 정비구역", jeongbiName: "" },
  // { polyName: "월내 주거환경개선구역", jeongbiName: "" },
];
