/** 실거래가 아파트명 → VR 투어 경로 매핑 */
export const APT_VR_MAP: Record<string, { regionId: string; slug: string }> = {
  "롯데캐슬":                          { regionId: "ocean", slug: "lotte" },
  "명지두산위브포세이돈":              { regionId: "ocean", slug: "doosan" },
  "명지오션시티한신휴플러스":          { regionId: "ocean", slug: "hansin" },
  "명지오션시티삼정그린코아":          { regionId: "ocean", slug: "samjung" },
  "엘크루블루오션4단지":               { regionId: "ocean", slug: "blueocean4" },
  "엘크루블루오션5단지":               { regionId: "ocean", slug: "blueocean5" },
  "엘크루블루오션6단지":               { regionId: "ocean", slug: "blueocean6" },
  "엘크루블루오션":                    { regionId: "ocean", slug: "blueocean5" },
  "엘크루솔마레":                      { regionId: "ocean", slug: "solmare" },
  "퀸덤1차아인슈타인타운":            { regionId: "ocean", slug: "qweendom_einstein" },
  "퀸덤1차에디슨타운":                { regionId: "ocean", slug: "qweendom_edison" },
  "퀸덤1차링컨타운":                  { regionId: "ocean", slug: "qweendom_lincoln" },
  "극동스타클래스":                    { regionId: "ocean", slug: "kukdong" },
  "명지국제신도시삼정그린코아더베스트": { regionId: "kukje", slug: "samjung" },
  "명지국제신도시호반베르디움1차":     { regionId: "kukje", slug: "hoban2" },
  "명지대방노블랜드오션뷰1차":        { regionId: "kukje", slug: "daebang1" },
  "명지대방노블랜드오션뷰2차":        { regionId: "kukje", slug: "daebang2" },
  "명지더웨스턴":                      { regionId: "kukje", slug: "thewestern" },
  "명지이편한세상":                    { regionId: "kukje", slug: "elife" },
  "e편한세상명지":                     { regionId: "kukje", slug: "elife" },
  "명지협성휴포레":                    { regionId: "kukje", slug: "hyupsung" },
  "부산명지중흥S-클래스에듀오션":     { regionId: "kukje", slug: "jungheung1" },
  "부산명지중흥S-클래스프라디움":     { regionId: "kukje", slug: "jungheung2" },
  "에일린의 뜰":                       { regionId: "kukje", slug: "eileen" },
  "더힐시그니처":                      { regionId: "kukje", slug: "thehill" },
  "명지1차 금강펜테리움 센트럴파크":  { regionId: "kukje", slug: "kumkang1" },
  "명지2차금강펜테리움센트럴파크":    { regionId: "kukje", slug: "kumkang2" },
  "더샵명지포스코월드2단지":          { regionId: "kukje", slug: "posco2" },
  "더샵명지포스코월드 2단지":         { regionId: "kukje", slug: "posco2" },
  "더샵명지퍼스트월드2단지":          { regionId: "kukje", slug: "posco2" },
  "더샵명지포스코월드3단지":          { regionId: "kukje", slug: "posco3" },
  "더샵명지포스코월드 3단지":         { regionId: "kukje", slug: "posco3" },
  "더샵명지퍼스트월드3단지":          { regionId: "kukje", slug: "posco3" },
};
